# 1일차 학습 목표
- 파이썬 기본 자료구조
- 기본 문법
- 패키지 활용
- numpy, pandas 자료구조
- 데이터 처리 

#1. 기본 자료구조

In [6]:
a = 2 #assignment
print( "abcddd  dasd ad asdas dAD AS" )

# 1,2,3,4,5
b = [ 1, 2, 3, 4, 5]
b

abcddd  dasd ad asdas dAD AS


[1, 2, 3, 4, 5]

In [ ]:
list1 = [ 20,10,5]  #리스트
#실행: 플레이버튼, 또는  ctrl+enter
print( list1 )
list1[ 1 ]#인덱싱
list1[ 1:3 ] #슬라이싱
list1[ 2 ] = 40
list1[ 0 ] = "data"
list1.append( 1000000000 )
list1.append( list1 )

12345


In [ ]:
tuple1 = ( 10,20,5 )
tuple1[1] = 40  #tuple의 값은은 수정 불가

In [9]:
# 다음과 리스트를 만들어보세요
# [    [1,2] ,  [3,4]  ,  [5,6] ]
# list2
list2 = [ [1,2], [3,4], [5,6]]
list2
#list2의 첫번째값
list2[ 0 ] * 2 #1,2값을 갖는 리스트

[1, 2, 1, 2]

In [ ]:
set1 = { 10,20, 5}
#set1[ 1 ]#인덱싱 불가

dict1 = {  'a':10,  'b':20,  'c':5}
dict1 #key-value
dict1['a']

10

In [ ]:
list3 = [ 3, 2.1, "A", 10]
list3[ 1:3 ]
list3[  2 ] = 100
list3.append( 99 )
list3

[3, 2.1, 100, 10, 99]

In [ ]:
list4 = [1,2,3]
list5 = [ [1,2], [3,4]    ]
list5

In [ ]:
dict2 = {'A':[1,2,3]  , 'B':[4,5,6] }
dict2

In [ ]:
list6 = [] 
list6.append( dict2 )
list6

[{'A': [1, 2, 3], 'B': [4, 5, 6]}]

#2. 조건문, 반복문, 예외처리 

In [15]:
l2 = [4,2,3]
l3 = []

for i in l2:
  l3.append( i*3 )

[ i*3 for i in l2 ]

[12, 6, 9]

In [ ]:
a = 90
a > 70

True

In [ ]:
if a > 70 :
  print("탕수육")

탕수육


In [ ]:
b=65
if b < 90 :
  if b <70:
    print("small")
  else:
    print("중간")
else:
  print("big")

small


In [ ]:
c=91
d=50
if (c > 90) | (d > 90):
  print("pizza")

pizza


In [ ]:
sales = [1,2,3,4,5]
for i in sales:
 if i > 3 :
  print(i)

[   i      for i in sales if i >3   ]

# sales2 = [ 10, 7, 12, 5, 19, 6] 일때, sales2의 각 값이 10보다 작으면
# 2배해서 출력하고, 그렇지 않으면 그냥 출력하세요
sales2 = [ 10, 7, 12, 5, 19, 6]
for i in sales2:
  if i > 10:
    print(i*2)
  else:
    print(i)

#sales2의 값에다가 모두 2를 곱해서 출력하기
#방법1
for i in sales2:
  print( i*2 )
#방법2
[ i*2 for i in sales2   ]

#반복문+조건문 다르게 표현현
[ i*2 for i in sales2 if i >3  ]

# sales3 = [ 10, 11, 8, 9, 12]
# sales3의 값 중에서 10보다 작은 숫자들만 선택을해서,
# 5를 더해서 리스트로 만드세요
sales3 = [ 10, 11, 8, 9, 12]
[ i+5 for i in sales3 if i < 10  ]
#위와 같은 작업을 하는 ....
result = []
for i in sales3:
  if i < 10:
    result.append(i+5)

- 1부터 10까지 값을 갖는 리스트
- 5보다 작은경우 2를 곱하고, 5이상은 3을 곱하세요
- 결과를 리스트로 만들어보세요
- 두 가지 방법으로 해보세요

In [ ]:
list0 = [1,2,3,4,5,6,7,8,9,10]
list00=[]
for i in list0:
  if i <5:
    list00.append( i*2 )
  else:
    list00.append( i*3 )

[ i *2 for i in list0 if i < 5]
[ i* 3 for i in list0 if i>=5 ]

In [ ]:
list1 = [1.0,2.0,0.0,3.0,4.0]
for i in list1:
  try:
    print( 1/i)
  except:
    pass    #print("error")

1.0
0.5
0.3333333333333333
0.25


#3. numpy의 array 

In [16]:
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 49.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 KB 34.9 MB/s eta 0:00:00


In [32]:
import numpy as np
a1 = np.array( [1,2] )
a1 * 2
a2 = np.array( [1,2,3,4])
a2
a3 = np.array(  [ [1,2],   [3 ,4] ] )
a3
a3.shape
a3.ndim
a2.shape
a2.reshape( 2,2  )
a3.reshape( 4)

array([1, 2, 3, 4])

In [39]:
a4 = np.array(  [[1,2,3], [4,5,6]])
a2[ 1:3 ]
a4

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
# 1~8까지 수를 갖는 1차원 array aa1를 만드세요
# aa1을 4행 2열짜리로 변환해서 aa2로 할당하세요
# aa2의 2~3행 1열의 값을 출력해보세요.

aa1 =np.array( [1,2,3,4,5,6,7,8])
aa2 = aa1.reshape( 4,2 )
aa2[ 1:3 ,  0  ]

array([3, 5])

In [ ]:
print(aa1 > 5)
aa1[ aa1 > 5  ] #True값을 갖는 ......출력
aa1[ (aa1>7) | (aa1<3) ] #True값을 갖는 ......출력

In [ ]:
import numpy as np
ar1 = np.array( [1,2,3])
ar1*ar1 #행렬 계산 아님
np.matmul( ar1, ar1) #행렬 계산...
ar2 = np.array( [[1,2],[3,4]] )
ar2.shape
ar1.shape
ar3 = np.array(  [[[1,2],[3,4]],[[5,6],[7,8]]])
ar3.shape

(2, 2, 2)

- array생성 및 차원 확인

In [50]:
import numpy as np
a = np.array( [0,1,2,3,4, 5.0])
a.shape #차원, 값의 개수
a.ndim
a.dtype #값의 종류, array->단일한 type의 값, 정수와 실수->실수 

dtype('float64')

In [ ]:
a.reshape( (3,2)  ) #a가 변경되지는 않음

array([0., 1., 2., 3., 4., 5.])

In [51]:
b = a.reshape((3,2))
print(b)
b.ndim
b.shape

[[0. 1.]
 [2. 3.]
 [4. 5.]]


(3, 2)

In [ ]:
b.reshape( (6, )) #2->1D로 변경

array([0., 1., 2., 3., 4., 5.])

- array 연산과 인덱싱

In [54]:
a

array([0., 1., 2., 3., 4., 5.])

In [ ]:
a[ [0,2,3] ]
b[  1  , 1     ]
b[ [0,2], 1]
b[ 0:2, 0]
b[ : , 0]  #1열만
b[  1 ,  :  ] #2행만

array([2., 3.])

In [ ]:
a > 3 
a[  [False, False, False, False,  True,  True] ]

a[   a>3   ] #3보다 큰 값만 출력
a[   a == 4 ]

print(b)
b[ b[:,1] >  3   ,  1 ] #2열의 값중에서 3보다 큰 값만 출력

#1열의 값 중에서 2이하인 값만 출력하고 10을 곱하세요
b[ b[:,0] <= 2,   0 ] * 10


[[0. 1.]
 [2. 3.]
 [4. 5.]]


array([ 0., 20.])

In [ ]:
#array 연산/인덱싱
a*2
a**2

[1,2,3,4,5]*2	#리스트와는 다름

#기본 인덱싱
a[ [2,3,4] ]
a[ np.array( [2,3,4]) ]	#인덱싱에 배열도 사용 가능

#논리 연산
a>4
a[ a>4 ]
a[ a>4 ] = 4



- 기본 활용 연습

In [ ]:
x = [0.0, 1, 2, 3, 4]
y = np.array(x)
y = np.array([[0.0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
np.shape(y)
y = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
np.shape(y)

x = [0, 1, 2, 3, 4] # Integers
y = np.array(x)
y.dtype

x = [0.0, 1, 2, 3, 4] # 0.0 is a float
y = np.array(x)
y.dtype

x = [0.0, 1, 2, 3, 4] # 하나라도 float이면 전체가 float임
y = np.array(x)
type(y)
y * y # Elementbyelement



array([ 0.,  1.,  4.,  9., 16.])

- 기본활용연습2: for 활용

In [ ]:
#array + for 같이 사용
a = np.array([[1, 2], [3, 4], [5, 6]], float) 
for x in a: 
    print(x)

#array 값 접근하기
x = np.array([1.0,2.0,3.0,4.0,5.0])
x[0]

x = np.array([[1.0,2,3],[4,5,6]])
x[1,2]


[1. 2.]
[3. 4.]
[5. 6.]


6.0

- 인덱싱, 슬라이싱

In [60]:
arr = np.arange(10, dtype=float).reshape((2, 5))
arr[1][3]

8.0

In [ ]:
#슬라이싱
arr[0] # 0번째 원소
arr[0, 3] # 1행 4열
arr[0][3] # 

arr[0, :] # 0행, 1차원 배열
arr[:, 0] # 0열, 1차원 배열
arr[:, :2] # 첫 2개 열
arr[:, 2:] # 2 위치 이후 열
arr2 = arr[:, 1:4] # 위치1 과 위치4 사이 열
print(arr2)

#슬라이싱2
arr2 = arr[:, [1,2,3]] # arr 배열의 복사본
print(arr2)
arr2[0, 0] = 44
print(arr2)
print(arr)
arr2 = arr[arr > 5] # arr 배열의 복사본
print(arr2)
arr2[0] = 44
print(arr2)
print(arr)

arr[arr > 5] = 0
print(arr)

[[1. 2. 3.]
 [6. 7. 8.]]
[[1. 2. 3.]
 [6. 7. 8.]]
[[44.  2.  3.]
 [ 6.  7.  8.]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[6. 7. 8. 9.]
[44.  7.  8.  9.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 0. 0. 0. 0.]]


- numpy 활용 통계량 계산

In [ ]:
x = np.arange(10.0)	#0~9까지 10개 숫자를 갖는 자료구조 생성
x.mean()

np.mean(x)
x= np.reshape(np.arange(20.0),(4,5))
np.mean(x,0)

np.median(x)

np.std(x)
np.var(x)

33.25

- NaN 값의 처리

In [ ]:
import numpy as np
np.array( [ 1,2,np.NAN,4])
np.NAN # not a number

array([ 1.,  2., nan,  4.])

In [63]:
#numpy.NAN:  숫자로 표현안되는 값
c = np.array( [1,2,np.NAN, 3,4])
print(c)
print( ~np.isnan(c) )
c[  ~np.isnan(c) ]

[ 1.  2. nan  3.  4.]
[ True  True False  True  True]


array([1., 2., 3., 4.])

In [ ]:
#numpy.NAN:  숫자로 표현안되는 값
c = np.array( [1,2,np.NAN, 3,4])
np.isnan(c)
c[ ~np.isnan(c) ]

np.mean( c[~np.isnan(c) ])

#NaN 함수
x = np.random.randn(4)
x[1] = np.NaN
sum(x)
np.nansum(x)
sum(x[np.logical_not(np.isnan(x))])
np.nansum(x) / sum(np.isnan(x))

-1.3121040542561104

- 그 외 유용한 기능

In [ ]:
#max, amax, argmax, min, amin, argmin
x = np.random.randn(3,4)
np.amax(x)
x.max()
x.max(0)	#column별 계산
x.max(1) #row별 계산

data = np.genfromtxt('creditset2.csv',delimiter=',', skip_header=1)
np.mean(data,0)	#column방향
np.median(data, 0)
np.var(data, 0)
np.std(data, 0)

array([1.43227451e+04, 1.32591337e+01, 3.04464858e+03, 3.48536583e-01])

#4. pandas의 dataframe 

In [ ]:
import pandas as pd
pd.DataFrame( [[1,2], [3,4]]  )
pd.DataFrame( b )

d1 = { "a": [1,2], "b": [3,4]}
pd.DataFrame( d1 )

df1 = pd.DataFrame( b, columns = ["v1", "v2"], 
             index=["a", "b", "c"])
df1

In [ ]:
#df1.info()
df1.columns
df1.index
df1.values

df1.v1  #특정 컬럼 선택, series
df1["v1"]
df1["v3"] = [1,2,3] #컬럼 추가


In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series( [1,2,3], index=["r1","r2","r3"]   )
s1.index
s1.values
s2 = pd.Series( [1,2,3], index=["r3","r2","r1"]   )

s1+s2

In [ ]:
df1=pd.DataFrame([[1,2],[3,4]],index=["r1","r2"],columns=["c1","c2"] )
#df1.index # df1.columns #df1.values
#df1.info()
#df1.describe()
df2=pd.DataFrame([[1,2], [3,4]],index=["r3","r2"],columns=["c3","c2"])
df1+df2
df1.columns=["c3", "c2"]
df1+df2

df1.describe()

In [94]:
#data.csv를 이용해서 data라는 데이터프레임 생성
import pandas as pd
data = pd.read_csv("data.csv")
#data.info()

#컬럼명을 확인
data.index
data.columns
data.values

data.shape

(1567, 49)

In [ ]:
data.iloc[ :, 1] #data.X86, data["X86"]

In [ ]:
#2-3열, 10-110행 부분집합으로 출력(iloc)
data.iloc[ 9:110   , 1:3   ]

#두번째 컬럼을 3가지 방법으로 출력
data[  "X86" ]
data[  ["X86", "X87"] ]#2개 이상의 컬럼
data.iloc[ :, 1 ]
data.X86

0       2.3895
1       2.3754
2       2.4532
3       2.4004
4       2.4530
         ...  
1562    2.3762
1563    2.4880
1564    2.4590
1565    2.3600
1566    2.3701
Name: X86, Length: 1567, dtype: float64

- data.csv를 읽은 data에서
- 각 변수의 요약값을 찾아보세요(describe() )
- 첫번째 변수와 두번째 변수를 더해서 새로운 변수 X0을 만들어보세요.
- 10-12행, 3-4열에 해당되는 값에 b array를 넣어보세요
- 5~6번 컬럼의 이름에서 X를 없애고 V를 넣으세요

In [105]:
data.describe()
data.columns
data["X0"] = data["X20"]+ data["X86"]
data.iloc[  9:12, 2:4 ] = b
data.columns[4:6] 

Index(['X113', 'X115'], dtype='object')

- CSV 읽기 

In [ ]:
!wget https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt -O ratings_train.txt
!wget https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt -O ratings_test.txt

In [ ]:
import pandas as pd

train_df = pd.read_csv('ratings_train.txt', sep='\t')
train_df.head(3)
train_df.info()
train_df['label'].value_counts( )

In [115]:
train_df.isnull().mean()
train_df.dropna().isnull().any()
#위 결과를 반영하려면, 1) 새롭게 할당, 2) inplace=True
train_df.isnull().mean()
train_df.dropna( inplace=True)  #원본에 반영, 화면에 미출력

-apply 함수 활용 missing value 처리

In [ ]:
import numpy as np
import pandas as pd
data = pd.read_csv("titanic_raw.csv")
data = data.replace('?', np.nan)	#치환, 데이터프레임 전체에 대해서 적용
data.info()
def get_first_cabin(row):
	try:
		return row.split()[0]	#공백을 기준으로 나눈 첫번째 값
	except:
		return np.nan	

In [126]:
get_first_cabin(data.cabin)
#data.cabin[3]
data['cabin'] = data['cabin'].apply(get_first_cabin) #cabin컬럼에 함수 적용용
#apply: 컬럼 단위의 루틴 적용, applymap: 데이터 프레임 전체에 적용

In [129]:
data.tail()	#head, tail, 앞뒤의 5개씩...
data.to_csv('titanic.csv', index=False)

- creditApprovalUCI.csv를 읽으셔서
- 컬럼별 결측치를 파악하고 (isnull() )
- 결측치를 제거한 데이터프레임을 만든 후(dropna() )
- 컬럼별 요약값을 test.csv로 저장하세요



In [135]:
credit = pd.read_csv("creditApprovalUCI.csv")
credit.isnull().mean()
print(credit.shape)
credit2 = credit.dropna() #inplace=True
credit2.describe().to_csv("test.csv")

(690, 16)


- Category Encoding

In [ ]:
import random
import pandas as pd
import numpy as np

data = pd.read_csv('crx.data', header=None)
data.shape
data

In [142]:
"A" + "B"
"A" + str(1)

'A1'

In [ ]:
varnames = ['A'+str(s) for s in range(1,17)]
varnames

data.columns = varnames
data.columns

In [155]:
data = data.replace('?', np.nan)
data["A16"].replace("+", 1).replace("-", 0)

0      1
1      1
2      1
3      1
4      1
      ..
685    0
686    0
687    0
688    0
689    0
Name: A16, Length: 690, dtype: int64

In [163]:
#A4컬럼에서 unique()를 쓰셔서 고유한 범주를 파악해보세요
#dropna()로 결측치 제거하시고...하세요
#각 범주를 수치로 map을 사용해서 변환해보세요 (0,1,2,3,4,5....)
#48분까지해보세요~

data["A4"].unique()
data["A4"].value_counts()
data["A4"].dropna().map(  { 'u':0, 'y':1, 'l':2})
data["A4"].value_counts()

u    519
y    163
l      2
Name: A4, dtype: int64

In [ ]:
#re-cast to float
data['A2'] = data['A2'].astype('float') #특정 컬럼의 type을 변환하는 메소드
data['A14'] = data['A14'].astype('float')

#re code target as binary
data['A16'] = data['A16'].map({'+':1, '-':0}) #딕셔너리 대로 값을 변환(키->밸류)




In [167]:
data["A2"].astype("float").dtype

dtype('float64')

In [170]:
[c for c in data.columns if data[c].dtypes!='O']	#범주형 변수

cat_cols = [c for c in data.columns if data[c].dtypes=='O']	#범주형 변수
num_cols = [c for c in data.columns if data[c].dtypes!='O']	#수치형 변수

In [ ]:
num_cols

['A2', 'A3', 'A8', 'A11', 'A14', 'A15', 'A16']

In [ ]:
#missing 처리: imputing
data[num_cols] = data[num_cols].fillna(0) #수치형변수만 선택->결측치->0으로 채우기기
data[cat_cols] = data[cat_cols].fillna('Missing')#범주형변수만 선택->결측치->Missing으로..

data.to_csv('creditApprovalUCI.csv', index=False) #행이름 제외하고 저장

- One Hot Encoding
 - onehot encoding 
 - 예: 성별->각 범주가 컬럼이 되고, 값은 1또는 0 또는 한 변수에서 값이 1과 0
 - 범주 수(k)-1개의 변수로 표현
 - 경우에 따라 범주 개수 만큼의 변수로 인코딩할 수 있음: 
 - DT와 같이 재귀적이고 분할하여 모델링하는 경우, 각 범주가 분리되는 것이 효과적

In [172]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

data = pd.read_csv('creditApprovalUCI.csv')

X_train, X_test, y_train, y_test = train_test_split(data.drop(labels=['A16'], axis=1), data['A16'], test_size=0.3,random_state=0)
X_train['A4'].unique()
X_train['A4'].isnull().mean()
X_train['A4'].value_counts()


u    363
y    115
l      1
Name: A4, dtype: int64

In [ ]:
pd.get_dummies( X_train['A4'], drop_first=False)

In [ ]:
tmp = pd.get_dummies( X_train['A4'], drop_first=False)#drop_first=True, OHE 할 때 컬럼을 줄여주는
tmp

In [ ]:
pd.get_dummies(X_train['A4'], drop_first=True)
tmp = pd.get_dummies(X_train['A4'], drop_first=True)	#k-1개로 인코딩
tmp.head()

In [ ]:
pd.get_dummies(X_train['A4'], drop_first=True, dummy_na=True)

/usr/local/lib/python3.9/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


l  u  y  NaN
596  0  1  0    0
303  0  1  0    0
204  0  0  1    0
351  0  0  1    0
118  0  1  0    0
..  .. .. ..  ...
359  0  1  0    0
192  0  1  0    0
629  0  1  0    0
559  0  1  0    0
684  0  1  0    0

[483 rows x 4 columns]

- 연습
 - df0.csv, df1.csv를 각각 df, df2로 읽으세요

In [176]:
import pandas as pd
df = pd.read_csv("df0.csv")
df2 = pd.read_csv("df1.csv")

In [ ]:
df2

In [180]:
def func1( input):
  if input > 1:
    return 1
  else:
    return 0

df2["target"] = df2.change.apply(func1)
df2.target

0    1
1    1
2    0
3    1
4    1
5    1
6    0
7    1
Name: target, dtype: int64

In [183]:
df.date.str.replace(".", "")

<ipython-input-183-423b12150e2e>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df.date.str.replace(".", "")


0    20230301
1    20230302
2    20230305
3    20230306
4    20230309
5    20230310
6    20230312
7    20230314
Name: date, dtype: object

In [184]:
df["date2"] = df.date.str.replace(".","") #str은 필수 

<ipython-input-184-c578bd77e856>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df["date2"] = df.date.str.replace(".","") #str은 필수


In [185]:
df2["date2"] = df2.date.str.replace("-","")

In [189]:
df2.shape

(8, 5)

In [ ]:
df3 = pd.concat( [df,df2 ], axis=1) #컬럼 방향으로 추가, 옆으로...
#axis=0 행방향 추가
print(df3)

In [ ]:
df4 = df3.groupby(['date2'])["value"].mean()

In [ ]:
#merge
df5 = pd.merge(df, df2, how="left", on="date2" )#왼쪽 데이터프레임(df)를 기준으로...
#두 데이터프레임의 공통적으로 있는 date2를 기준으로...
df5

In [ ]:
print(df5.dropna())#원본에 미적용
df5.dropna(inplace=True)#원본에 적용

In [ ]:
#df5에서 date2를 기준으로 value2의 평균을 group by
#df, df2를 merge할 때 , how="right"로 해보시고 결과를 df6 

In [ ]:
df5.groupby(['date2'])["value"].mean() #df5에서 date2기준, value컬럼의 평균

date2
20230301    10005.0
20230302    10103.0
20230305    10089.0
20230309    10005.0
20230310    10103.0
20230314    10115.0
Name: value2, dtype: float64

In [ ]:
pd.merge( df2, df, how="left", on="date2")

date_x  value  change  target     date2      date_y  value2
0  2023-03-01   1000     1.5       1  20230301  2023.03.01   10005
1  2023-03-02   1010     1.3       1  20230302  2023.03.02   10103
2  2023-03-05   1008     0.9       0  20230305  2023.03.05   10089
3  2023-03-05   1011     1.5       1  20230305  2023.03.05   10089
4  2023-03-09   1000     1.5       1  20230309  2023.03.09   10005
5  2023-03-10   1010     1.3       1  20230310  2023.03.10   10103
6  2023-03-14   1008     0.9       0  20230314  2023.03.14   10115
7  2023-03-14   1011     1.5       1  20230314  2023.03.14   10115

In [ ]:
!pip install pykrx 

In [196]:
from pykrx import stock, bond
df3 = stock.get_market_ohlcv("20220720", "20220810", "005930" )
df4 = stock.get_market_ohlcv("20220730", "20220820", "005380" )
df5 = stock.get_market_ohlcv("20220720", "20220810", "005380" )

In [ ]:
# 005930외의 다른 종목 코드를 찾으셔서, 0730~0820에 대한 주가정보를 수집하세요
# df4
# 위의 종목코드를 0720~0810에 대해서도 주가정보를 수집하세요
# df5
# 1. df3과 df4를 merge 해보세요(날짜...)
pd.merge(df3, df4, on="날짜")
# 2. df3과 df5를 concat로 합쳐보세요.
pd.concat( [df3, df5], axis=1 )

# Date, time 실습

- Dates, Time 변수 

In [ ]:
import pandas as pd
pd.date_range(start='1/1/2018', end='1/08/2018')
pd.date_range(start='2018-01-01', end='1/08/2018')
pd.date_range('2019-03-05', periods=20, freq='D')
pd.date_range('2019-03-05', periods=20, freq='3M')

In [ ]:
pd.date_range('2019-03-05', periods=20, freq='3M')
pd.date_range('2019-03-05', periods=20, freq='T')#Time간격
pd.date_range('2019-03-05', periods=20, freq='3H')

In [203]:
rng_ = pd.date_range('2019-03-05', periods=20, freq='T')
rng_
type(rng_)

pandas.core.indexes.datetimes.DatetimeIndex

In [ ]:
df = pd.DataFrame({'date': rng_})
df.head()
df.shape
df.dtypes
df["date"].dt.date
df["date"].dt.time

In [ ]:
df['date'].dt.time
df['date_part'] = df['date'].dt.date
df['date_part'].head()

df['time_part'] = df['date'].dt.time
df['time_part'].head()

In [209]:
df = pd.DataFrame({'date_var':['Jan-2015', 'Apr-2013', 'Jun-2014','Jan-2015']})
pd.to_datetime(df['date_var'])
df['datetime_var'] = pd.to_datetime(df['date_var'])

In [211]:
df['date'] = df['datetime_var'].dt.date
df['time'] = df['datetime_var'].dt.time
df

date_var datetime_var        date      time
0  Jan-2015   2015-01-01  2015-01-01  00:00:00
1  Apr-2013   2013-04-01  2013-04-01  00:00:00
2  Jun-2014   2014-06-01  2014-06-01  00:00:00
3  Jan-2015   2015-01-01  2015-01-01  00:00:00

In [212]:
#달과 연도 표시
import numpy as np
import pandas as pd
rng_ = pd.date_range('2019-03-05', periods=20, freq='M')
df = pd.DataFrame({'date': rng_})
df.head()
df['year'] = df['date'].dt.year
df.head()
df['month'] = df['date'].dt.month
df.head()
df['day'] = df['date'].dt.day
df.head()
df['quarter'] = df['date'].dt.quarter
df.head()

date  year  month  day  quarter
0 2019-03-31  2019      3   31        1
1 2019-04-30  2019      4   30        2
2 2019-05-31  2019      5   31        2
3 2019-06-30  2019      6   30        2
4 2019-07-31  2019      7   31        3

In [ ]:
df['quarter'].isin( [1,2] ) #[1,2]에 나오는 값들 하나라도 포함되었으면 True

In [215]:
np.where( df['quarter'].isin([1,2]), "T" , "F"  )

array(['T', 'T', 'T', 'T', 'F', 'F', 'F', 'F', 'F', 'F', 'T', 'T', 'T',
       'T', 'T', 'T', 'F', 'F', 'F', 'F'], dtype='<U1')

In [218]:
2 in [2,3]

True

In [ ]:
np.where(df['quarter'].isin([1,2]), "1학기", "2학기") 

In [ ]:
df['semester'] = np.where(df['quarter'].isin([1,2]), 1, 2)  #np의 if 기능능
df.head()

In [219]:
#day week표현
import numpy as np
import pandas as pd
rng_ = pd.date_range('2019-03-05', periods=20, freq='D')
df = pd.DataFrame({'date': rng_})
df.head()
df['day_mo'] = df['date'].dt.day
df.head()

date  day_mo
0 2019-03-05       5
1 2019-03-06       6
2 2019-03-07       7
3 2019-03-08       8
4 2019-03-09       9

In [ ]:
df['date'].dt.dayofweek

In [ ]:
df['day_week'] = df['date'].dt.dayofweek#월요일 0부터 시작.
df
df['day_week'].unique()

In [ ]:
df['week'] = df['date'].dt.week
df.head()

In [ ]:
#datetime에서 time 추출
import numpy as np
import pandas as pd

rng_ = pd.date_range('2019-03-05', periods=20, freq='1h15min10s')
df = pd.DataFrame({'date': rng_})
df.head()
df['hour'] = df['date'].dt.hour
df['min'] = df['date'].dt.minute
df['sec'] = df['date'].dt.second
df.head()
df.info()

In [ ]:
df[['h','m','s']] = pd.DataFrame(
    [   (x.hour, x.minute, x.second)    for x in df['date']]#한개씩..
)
df.head()
#to_datetime()를 사용하면 object에서 datetime으로 변환
df['is_morning'] = np.where( (df['hour'] < 12) & (df['hour'] > 6), 
                            1, 0 )
df.head()


In [ ]:
#datetime 변수간 측정된 기간 표현
import datetime
import numpy as np
import pandas as pd

rng_hr = pd.date_range('2019-03-05', periods=20, freq='H')
rng_month = pd.date_range('2019-03-05', periods=20, freq='M')
df = pd.DataFrame({'date1': rng_hr, 'date2': rng_month})
df.head()
df['elapsed_days'] = (df['date2'] - df['date1']).dt.days
df.head(2)

date1      date2  elapsed_days
0 2019-03-05 00:00:00 2019-03-31            26
1 2019-03-05 01:00:00 2019-04-30            55

In [ ]:
df['months_passed'] = ((df['date2'] - df['date1']) / np.timedelta64(1, 'M')) #시간 간격, 월
df['months_passed'] = np.round(df['months_passed'],0) #반올림림
df.head()

df['diff_seconds'] = (df['date2'] - df['date1'])/np.timedelta64(1,'s')  #시간 간격, 초
df['diff_minutes'] = (df['date2'] - df['date1'])/np.timedelta64(1,'m')  #시간 간격, 분
df.head()

In [ ]:
df['to_today'] = (datetime.datetime.today() - df['date1'])  #오늘까지의 시간
df.head()