<a href="https://colab.research.google.com/github/skdmldyd23/AI_Edu/blob/main/AI_1%EC%9D%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1일차 학습 목표
- 파이썬 기본 자료구조
- 기본 문법
- 패키지 활용
- numpy, pandas 자료구조
- 데이터 처리 연습

#1. 기본 자료구조

In [ ]:
#좌측 상단 +코드로 코드셀 추가 가능
print("Hello, World!")

Hello world


In [ ]:
list1 = [ 20,10,5]  #리스트
#실행: 플레이버튼, 또는  ctrl+enter
print( list1 )
list1[ 1 ]#인덱싱
list1[ 1:3 ] #슬라이싱
list1[ 2 ] = 40
list1[ 0 ] = "data" #Any Data Type
list1.append( 1000000000 )
list1.append( list1 )

[20, 10, 5, 1]
10
[10, 5]
['data', 10, 40, 1, 1000000000, [...]]


In [ ]:
tuple1 = ( 10,20,5 )
tuple1[1] = 40  #tuple의 값은은 수정 불가

In [ ]:
#다음과 같은 리스트를 만들어보세요.
#[[1,2],[3,4],[5,6]]
list = [[1,2],[3,4],[5,6]]
list
#list의 첫번째 값
list[0]   # = 1,2의 값을 가진 리스트
list[0]*2 # = 1,2,1,2

[1, 2, 1, 2]

In [ ]:
set1 = { 10,20, 5}
#set1[ 1 ]#인덱싱 불가
dict1 = {  'a':10,  'b':20,  'c':5}
dict1 #key-value
dict1['a']

10

In [ ]:
list3 = [ 3, 2.1, "A", 10]
list3[ 1:3 ]
list3[  2 ] = 100
list3.append( 99 )
list3

[3, 2.1, 100, 10, 99]

In [ ]:
list4 = [1,2,3]
list5 = [ [1,2], [3,4]    ]
list5

In [ ]:
dict2 = {'A':[1,2,3]  , 'B':[4,5,6] }
dict2

In [ ]:
list6 = [] 
list6.append( dict2 )
list6

[{'A': [1, 2, 3], 'B': [4, 5, 6]}]

## #2. 조건문, 반복문, 예외처리 

In [ ]:
l2 = [4,2,3]
l3 = []

#반복문으로 곱하기
for i in l2:
  l3.append(i*3)
l3

#다른 스타일
l4 = [i*4 for i in l2]
l4

#if문 적용
sales = [1,2,3,4,5]
print("test - ", [i for i in sales if i > 3])

[16, 8, 12]

In [ ]:
#- 1부터 10까지 값을 갖는 리스트
# 홀수 *2, 짝수 *3
# 결과는 리스트
# 두 가지 방법

#1
list = [1,2,3,4,5,6,7,8,9,10]
result = []
for i in list:
  if i < 5:
    result.append(i*2)
  else:
    result.append(i*3)
print(result)

#2 
list = [1,2,3,4,5,6,7,8,9,10]
result = []
result.append([i*2 for i in list if i < 5])
result.append([i*3 for i in list if i >= 5])
print(result)

In [ ]:
list = [1,0,2,0,3,0,0,4,0,0,0,5,0]
for i in list:
  try:
    print(1/i)
  except:
    print(i," - error")
    pass

1.0
0  - error
0.5
0  - error
0.3333333333333333
0  - error
0  - error
0.25
0  - error
0  - error
0  - error
0.2
0  - error


In [ ]:
a = 90
a > 70

True

In [ ]:
if a > 70 :
  print("탕수육")

탕수육


In [ ]:
b=65
if b < 90 :
  if b <70:
    print("small")
  else:
    print("중간")
else:
  print("big")

small


In [ ]:
c=91
d=50
if (c > 90) | (d > 90):
  print("pizza")

pizza


In [ ]:
sales = [1,2,3,4,5]
for i in sales:
 if i > 3 :
  print(i)

# sales2 = [ 10, 7, 12, 5, 19, 6] 일때, sales2의 각 값이 10보다 작으면
# 2배해서 출력하고, 그렇지 않으면 그냥 출력하세요
sales2 = [ 10, 7, 12, 5, 19, 6]
for i in sales2:
  if i > 10:
    print(i*2)
  else:
    print(i)

#sales2의 값에다가 모두 2를 곱해서 출력하기
#방법1
for i in sales2:
  print( i*2 )
#방법2
[ i*2 for i in sales2   ]

#반복문+조건문 다르게 표현현
[ i*2 for i in sales2 if i >3  ]

# Q. sales3 = [ 10, 11, 8, 9, 12]
# sales3의 값 중에서 10보다 작은 숫자들만 선택을해서,
# 5를 더해서 리스트로 만드세요
sales3 = [ 10, 11, 8, 9, 12]
[ i+5 for i in sales3 if i < 10  ]
#위와 같은 작업을 하는 ....
result = []
for i in sales3:
  if i < 10:
    result.append(i+5)

4
5
test -  [4, 5]
10
7
24
5
38
6
20
14
24
10
38
12


In [ ]:
list1 = [1.0,2.0,0.0,3.0,4.0]
for i in list1:
  try:
    print( 1/i)
  except:
    pass    #print("error")

1.0
0.5
0.3333333333333333
0.25


#3. numpy의 array 

In [ ]:
#!로 시작하면 터미널로 시작하는 명령어
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 24.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 KB 38.3 MB/s eta 0:00:00


In [ ]:
import numpy as np
#import로 메모리에 올림
#from 패키지 import 함수로도 가능

#array로 감싸면 array로 변경
ar1 = np.array( [1,2,3])

# ndim == 몇차원인지 / shape == 각 차원의 개수
ar2 = np.array( [[1,2],[3,4]] )
ar2.shape
ar1.shape
ar3 = np.array(  [[[1,2],[3,4]],[[5,6],[7,8]]])
ar3.shape

#reshape 개수에 맞게 차원 변형 가능
#데이터가 변경되진않음
a4 = np.array([1,2,3,4,5,6,7,8])
a4.reshape(4,2)

#행렬 복사가 아닌 대응되는 위치의 곱
ar1*ar1

#행렬 곱
np.matmul( ar1, ar1)

array([1, 2, 3, 4, 5, 6, 7, 8])

- array생성 및 차원 확인

In [ ]:
import numpy as np
a = np.array( [0,1,2,3,4, 5.0])
a.shape #차원, 값의 개수
a.ndim
a.dtype #값의 종류, array->단일한 type의 값, 정수와 실수->실수 

dtype('float64')

In [ ]:
a.reshape( (3,2)  ) #a가 변경되지는 않음

array([0., 1., 2., 3., 4., 5.])

In [ ]:
b = a.reshape((3,2))
print(b)
b.ndim
b.shape

[[0. 1.]
 [2. 3.]
 [4. 5.]]


(3, 2)

In [ ]:
b.reshape( (6, )) #2->1D로 변경

array([0., 1., 2., 3., 4., 5.])

- array 연산과 인덱싱

In [ ]:
ar = np.array([[1,2,3],[4,5,6]])
ar[1, 1]
ar[0:2, 0]
ar[ :, 0]  #1열만
ar[1, :] #2행만
ar[0:2, 1:3]

#Q. 1~8까지 수를 갖는 1차원 array aa1 만들기.
#aa1을 4행 2열로 변경
#aa2의 2-3행 1열의 값을 출력
aa1 = np.array([1,2,3,4,5,6,7,8])
aa2 = aa1.reshape(4,2)
aa2[1:3, 0]

array([3, 5])

In [ ]:
a = np.array([1,2,3,4,5])

a>3
#array([False, False, False,  True,  True])

a[a>3]
#array([4, 5])

a[(a>2)&(a<4)]
#array([3])

a[(a<=2)|(a>4)]
#array([1, 2, 5])

array([1, 2, 5])

In [ ]:
#array 연산/인덱싱
a*2
a**2

[1,2,3,4,5]*2	#리스트와는 다름

#기본 인덱싱
a[ [2,3,4] ]
a[ np.array( [2,3,4]) ]	#인덱싱에 배열도 사용 가능

#논리 연산
a>4
a[ a>4 ]
a[ a>4 ] = 4



- 기본 활용 연습

In [ ]:
x = [0.0, 1, 2, 3, 4]
y = np.array(x)
y = np.array([[0.0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
np.shape(y)
y = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
np.shape(y)

x = [0, 1, 2, 3, 4] # Integers
y = np.array(x)
y.dtype

x = [0.0, 1, 2, 3, 4] # 0.0 is a float
y = np.array(x)
y.dtype

x = [0.0, 1, 2, 3, 4] # 하나라도 float이면 전체가 float임
y = np.array(x)
type(y)
y * y # Elementbyelement



array([ 0.,  1.,  4.,  9., 16.])

- 기본활용연습2: for 활용

In [ ]:
#array + for 같이 사용
a = np.array([[1, 2], [3, 4], [5, 6]], float) 
for x in a: 
    print(x)

#array 값 접근하기
x = np.array([1.0,2.0,3.0,4.0,5.0])
x[0]

x = np.array([[1.0,2,3],[4,5,6]])
x[1,2]


[1. 2.]
[3. 4.]
[5. 6.]


6.0

- 인덱싱, 슬라이싱

In [ ]:
#슬라이싱
arr = np.arange(10, dtype=float).reshape((2, 5))
arr[0] # 0번째 원소
arr[0, 3] # 0행 3열
arr[0][3] # 0행3열

arr[0, :] # 0행, 1차원 배열
arr[:, 0] # 0열, 1차원 배열
arr[:, :2] # 첫 2개 열
arr[:, 2:] # 2 위치 이후 열
arr2 = arr[:, 1:4] # 위치1 과 위치4 사이 열
print(arr2)

#슬라이싱2
arr2 = arr[:, [1,2,3]] # arr 배열의 복사본
print(arr2)
arr2[0, 0] = 44
print(arr2)
print(arr)
arr2 = arr[arr > 5] # arr 배열의 복사본
print(arr2)
arr2[0] = 44
print(arr2)
print(arr)

arr[arr > 5] = 0
print(arr)



[[1. 2. 3.]
 [6. 7. 8.]]
[[1. 2. 3.]
 [6. 7. 8.]]
[[44.  2.  3.]
 [ 6.  7.  8.]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[6. 7. 8. 9.]
[44.  7.  8.  9.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 0. 0. 0. 0.]]


- numpy 활용 통계량 계산

In [ ]:
x = np.arange(10.0)	#0~9까지 10개 숫자를 갖는 자료구조 생성
x.mean()

np.mean(x)
x= np.reshape(np.arange(20.0),(4,5))
np.mean(x,0)

np.median(x)

np.std(x)
np.var(x)

33.25

- NaN 값의 처리

In [ ]:
import numpy as np
np.array( [ 1,2,np.NAN,4])
np.NAN # not a number

nan

In [ ]:
#numpy.NAN:  숫자로 표현안되는 값
c = np.array( [1,2,np.NAN, 3,4])
c[  ~np.isnan(c) ]

array([1., 2., 3., 4.])

In [ ]:
#numpy.NAN:  숫자로 표현안되는 값
c = np.array( [1,2,np.NAN, 3,4])
np.isnan(c)
c[ ~np.isnan(c) ]

np.mean( c[~np.isnan(c) ])

#NaN 함수
x = np.random.randn(4)
x[1] = np.NaN
sum(x)
np.nansum(x)
sum(x[np.logical_not(np.isnan(x))])
np.nansum(x) / sum(np.isnan(x))



-1.3121040542561104

- 그 외 유용한 기능

In [ ]:
#max, amax, argmax, min, amin, argmin
x = np.random.randn(3,4)
np.amax(x)
x.max()
x.max(0)	#column별 계산
x.max(1) #row별 계산

data = np.genfromtxt('creditset2.csv',delimiter=',', skip_header=1)
np.mean(data,0)	#column방향
np.median(data, 0)
np.var(data, 0)
np.std(data, 0)

FileNotFoundError: ignored

#4. pandas의 dataframe 

In [ ]:
import pandas as pd

b= [[1,2],[3,4]]
#데이터프레임 만드는 법
pd.DataFrame([[1,2], [3,4]])
pd.DataFrame(b)

#딕셔너리구조로 만들면 컬럼 이름 지정 가능
d1 = {"a":[1,2], "b":[3,4]}
pd.DataFrame(d1)

#col, row 이름 지정
pd.DataFrame(b, columns = ["col1", "col2"], index = ["row1","row2"])

df1 = pd.DataFrame(b, columns = ["col1", "col2"], index = ["row1","row2"])

#모든 정보를 볼 수 있음.
#df1.info()

#데이터 프레임은 아래의 3개의 구성으로 되어있다.
df1.columns
df1.index
df1.values

#특정 컬럼 선택해서 확인 가능
df1.col1
df1["col1"]

#데이터 추가 가능
df1["col3"] = [7,8] 

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    2 non-null      int64
 1   col2    2 non-null      int64
 2   col3    2 non-null      int64
dtypes: int64(3)
memory usage: 64.0+ bytes


<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    2 non-null      int64
 1   col2    2 non-null      int64
dtypes: int64(2)
memory usage: 156.0+ bytes


In [ ]:
import pandas as pd
import numpy as np

s1 = pd.Series( [1,2,3], index=["r1","r2","r3"]   )
s2 = pd.Series( [1,2,3], index=["r3","r2","r1"]   )

#Series == columns 없음
s1.index
s1.values

#각 인덱스별로 덧셈이 된다.
s1+s2 #4 4 4

df1=pd.DataFrame([[1,2],[3,4]],index=["r1","r2"],columns=["c1","c2"] )
df2=pd.DataFrame([[1,2], [3,4]],index=["r3","r2"],columns=["c3","c2"])

#df1.index # df1.columns #df1.values
df1.info()

#c2외 겹치지 않기에r2,c2만 8, 나머지 NaN 
df1+df2

#컬럼명 수정하면 잘 더해짐
df1.columns=["c3", "c2"]
df1+df2

#요약 값 출력
df1.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, r1 to r2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c1      2 non-null      int64
 1   c2      2 non-null      int64
dtypes: int64(2)
memory usage: 48.0+ bytes


c3        c2
count  2.000000  2.000000
mean   2.000000  3.000000
std    1.414214  1.414214
min    1.000000  2.000000
25%    1.500000  2.500000
50%    2.000000  3.000000
75%    2.500000  3.500000
max    3.000000  4.000000

In [ ]:
#data.csv를 이용해서 data라는 데이터프레임 생성
import pandas as pd
data = pd.read_csv("data.csv")

#컬럼명을 확인
data.index
data.columns
data.values

#data.info()

#몇행 몇열 인가.
data.shape

#2-3열, 10-110행 부분집합으로 출력(iloc)
data.iloc[ 9:110   , 1:3   ]

#두번째 컬럼을 3가지 방법으로 출력
#data.X86
#data[  "X86" ]
#data.iloc[ :, 1 ]

#data[  ["X86", "X87"] ]#2개 이상의 컬럼


X86     X87
9    2.4069  0.9680
10   2.4532  0.9883
11   2.3588  0.9695
12   2.3652  0.9642
13   2.3588  0.9890
..      ...     ...
105  2.4392  0.9887
106  2.4367  0.9875
107  2.4077  0.9824
108  2.3746  0.9894
109  2.3633  0.9847

[101 rows x 2 columns]

In [ ]:
# Q. data,csv를 읽은 data에서 
# 각 변수의 요약 값 찾기
# 첫번째 변수와 두번째 변수를 더해서 x0 만들기
# 10-12행, 3-4열에 해당되는 값에 b라는 어레이에 넣기
# 5-6번 컬럼명 x -> v 변경
import pandas as pd
data = pd.read_csv("data.csv")

#1
#data.describe()

#2.
data["X0"] = data["X20"] + data["X86"]

#3.
b = data.iloc[9:12, 2:4]
b

#4.
#data.columns = [..., "V113", "V115", ...]

ValueError: ignored

- CSV 읽기 

In [ ]:
!wget https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt -O ratings_train.txt
!wget https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt -O ratings_test.txt

--2023-04-10 05:34:21--  https://github.com/rickiepark/python-machine-learning-book-3rd-edition/raw/master/ch08/ratings_train.txt
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/rickiepark/python-machine-learning-book-3rd-edition/master/ch08/ratings_train.txt [following]
--2023-04-10 05:34:21--  https://raw.githubusercontent.com/rickiepark/python-machine-learning-book-3rd-edition/master/ch08/ratings_train.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14628807 (14M) [text/plain]
Saving to: ‘ratings_train.txt’

ratings_train.txt   100%[===================>]  13.95M  --.-KB/s    in 0.08s   



In [ ]:
import pandas as pd

train_df = pd.read_csv('ratings_train.txt', sep='\t')

#상위 데이터 확인
#train_df.head(3)

#각 컬럼이 가지는 유니크한 데이터의 개수("select count(1) from dual group by col")
#train_df['label'].value_counts()

#document 타입이 non-null이 5개가 빈다.
#missing value 처리 해야함
#train_df.info()

#isnull의 평균은 각 missing Value의 비율을 알 수 있다.
train_df.isnull().mean()

#결측치를 그냥 날림(dropna) / true값이 하나라도 있는가 (isnull().any())
train_df.dropna().isnull().any()

#위의 결과를 반영하려면 새롭게 할당
#1) train_df = train_df.dropna()
#2) dropna(inplace=True)
train_df.dropna(inplace=True)

-apply 함수 활용 missing value 처리

In [ ]:
import numpy as np
import pandas as pd
data = pd.read_csv("titanic_raw.csv")
# 1. 결측치 어떻게 처리

#data.info()를 보면 개수만 보면 결측이 없다.
#but. age가 object가 되어있다. / 데이터에 ?가 들어가있다.
data = data.replace('?', np.nan)	#치환
#data.info()

# 2. Cabin 어떻게 처리
#Cabin이 공백을 기준으로 여러 값이 있어서 가장 처음 값만 쓰기로 함.
#함수를 만든다. / 공백 기준으로 0번째 or nan 리턴
def get_first_cabin(row):
	try:
		return row.split()[0]	#공백을 기준으로 나눈 첫번째 값
	except:
		return np.nan

#apply = 각 컬럼에 함수를 실행
#applymap = 데이터 프레임 전체에 적용
data['cabin'] = data['cabin'].apply(get_first_cabin) #cabin컬럼에 함수 적용
data.head()

#저장 후 확인
data.to_csv('titanic.csv', index=False)


In [ ]:
import numpy as np
import pandas as pd
#Q. creditApprovalUCI
#결측치 파악
#결측치 제거 데이터프레임 생성
#값 저장

data = pd.read_csv("creditApprovalUCI.csv")

#1. 결측치
data.isnull().mean()

#2. 제거
data.dropna(inplace=True)

#저장
data.to_csv("after_creditApprovalUCI.csv")

- Category Encoding

In [ ]:
import random
import pandas as pd
import numpy as np

#헤더가 없음.
data = pd.read_csv('crx.data', header=None)

#헤더 생성
varnames = ['A'+str(s) for s in range(1,17)]
data.columns = varnames
data.info()

data = data.replace('?', np.nan)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A1      690 non-null    object 
 1   A2      690 non-null    object 
 2   A3      690 non-null    float64
 3   A4      690 non-null    object 
 4   A5      690 non-null    object 
 5   A6      690 non-null    object 
 6   A7      690 non-null    object 
 7   A8      690 non-null    float64
 8   A9      690 non-null    object 
 9   A10     690 non-null    object 
 10  A11     690 non-null    int64  
 11  A12     690 non-null    object 
 12  A13     690 non-null    object 
 13  A14     690 non-null    object 
 14  A15     690 non-null    int64  
 15  A16     690 non-null    object 
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB


0      1
1      1
2      1
3      1
4      1
      ..
685    0
686    0
687    0
688    0
689    0
Name: A16, Length: 690, dtype: int64

In [ ]:
#re-cast to float
#특정 컬럼의 type을 변환하는 메소드
data['A2'] = data['A2'].astype('float') 
data['A14'] = data['A14'].astype('float')

#변환할 데이터가 많아지면 보기 힘듦
data["A16"].replace("+", 1).replace("-", 0)

#map으로 변환가능
data['A16'] = data['A16'].map({'+':1, '-':0}) #딕셔너리 대로 값을 변환(키->밸류)

#Q 
# 결측치 제거
# a4의 unique() 파악
# map으로 범주를 수치로
data['A4'].dropna().unique()
t1 = data['A4'].dropna().map({"u":1, "y":2, "l":3})
t1


0      1
1      1
2      1
3      1
4      1
      ..
685    2
686    1
687    2
688    1
689    1
Name: A4, Length: 684, dtype: int64

In [ ]:
#data["A1"].dtype로 타입을 볼 수 있음 O== object, float = float64 등등

#Object만 뽑으니까 범주형 변수
cat_cols = [c for c in data.columns if data[c].dtypes=='O']

#Object를 뽑지않으니 수치형 변수
num_cols = [c for c in data.columns if data[c].dtypes!='O']

#missing 처리: inputing 
data[num_cols] = data[num_cols].fillna(0) #수치형변수만 선택->결측치->0으로 채우기기
data[cat_cols] = data[cat_cols].fillna('Missing')#범주형변수만 선택->결측치->Missing으로..

data.to_csv('creditApprovalUCI.csv', index=False) #행이름 제외하고 저장


- One Hot Encoding
 - onehot encoding 
 - 예: 성별->각 범주가 컬럼이 되고, 값은 1또는 0 또는 한 변수에서 값이 1과 0
 - 범주 수(k)-1개의 변수로 표현
 - 경우에 따라 범주 개수 만큼의 변수로 인코딩할 수 있음: 
 - DT와 같이 재귀적이고 분할하여 모델링하는 경우, 각 범주가 분리되는 것이 효과적

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

data = pd.read_csv('creditApprovalUCI.csv')

X_train, X_test, y_train, y_test = train_test_split(data.drop(labels=['A16'], axis=1), data['A16'], test_size=0.3,random_state=0)
X_train['A4'].unique()
X_train['A4'].isnull().mean()
X_train['A4'].value_counts()


u    363
y    115
l      1
Name: A4, dtype: int64

In [ ]:
#범주형 변수를 만들어주는 pandas 함수 get_dummies
#drop_first=True, OHE 할 때 컬럼을 줄여줌
tmp = pd.get_dummies( X_train['A4'], drop_first=False)
tmp

l  u  y
596  0  1  0
303  0  1  0
204  0  0  1
351  0  0  1
118  0  1  0
..  .. .. ..
359  0  1  0
192  0  1  0
629  0  1  0
559  0  1  0
684  0  1  0

[483 rows x 3 columns]

In [ ]:
pd.get_dummies(X_train['A4'], drop_first=True)
tmp = pd.get_dummies(X_train['A4'], drop_first=True)	#k-1개로 인코딩
tmp.head()

u  y
596  1  0
303  1  0
204  0  1
351  0  1
118  1  0

In [ ]:
pd.get_dummies(X_train['A4'], drop_first=True, dummy_na=True)

u  y  NaN
596  1  0    0
303  1  0    0
204  0  1    0
351  0  1    0
118  1  0    0
..  .. ..  ...
359  1  0    0
192  1  0    0
629  1  0    0
559  1  0    0
684  1  0    0

[483 rows x 3 columns]

- 연습
 - df0.csv, df1.csv를 각각 df, df2로 읽으세요

In [ ]:
import pandas as pd
df = pd.read_csv("df0.csv")
df2 = pd.read_csv("df1.csv")

#두 파일은 형식이 다름, df1은 중복되는 날짜가 있음.
#df0 date == 2023.03.01
#df1 date == 2023-03-01

In [ ]:
df2

In [ ]:
#1보다 크면 1 아니면 0
def func1( input):
  if input > 1:
    return 1
  else:
    return 0

df2["target"] = df2.change.apply(func1)
df2.target

In [ ]:
df.date

0    2023.03.01
1    2023.03.02
2    2023.03.05
3    2023.03.06
4    2023.03.09
5    2023.03.10
6    2023.03.12
7    2023.03.14
Name: date, dtype: object

In [ ]:
#yyyyMMdd 형식으로 변환 
#str은 필수 
df["date2"] = df.date.str.replace(".","")
df2["date2"] = df2.date.str.replace("-","")

In [ ]:
#단순하게 append느낌으로 추가
#컬럼 방향으로 추가 axis=1
#행 방향으로 추가 axis=0
df3 = pd.concat( [df,df2 ], axis=1)
print(df3)

         date  value2     date2        date  value  change  target     date2
0  2023.03.01   10005  20230301  2023-03-01   1000     1.5       1  20230301
1  2023.03.02   10103  20230302  2023-03-02   1010     1.3       1  20230302
2  2023.03.05   10089  20230305  2023-03-05   1008     0.9       0  20230305
3  2023.03.06   10115  20230306  2023-03-05   1011     1.5       1  20230305
4  2023.03.09   10005  20230309  2023-03-09   1000     1.5       1  20230309
5  2023.03.10   10103  20230310  2023-03-10   1010     1.3       1  20230310
6  2023.03.12   10089  20230312  2023-03-14   1008     0.9       0  20230314
7  2023.03.14   10115  20230314  2023-03-14   1011     1.5       1  20230314


In [ ]:
#merge == join과 같음
#왼쪽 데이터프레임(df)를 기준으로
#on 기준으로
df5 = pd.merge(df, df2, how="left", on="date2" )
df5
print(df5.dropna())#원본에 미적용
df5.dropna(inplace=True)#원본에 적용

In [ ]:
#df5에서 date2를 기준으로 value2의 평균을 group by
#df, df2를 merge할 때 , how="right"로 해보시고 결과를 df6 

In [ ]:
df5.groupby(['date2'])["value"].mean() #df5에서 date2기준, value컬럼의 평균

date2
20230301    10005.0
20230302    10103.0
20230305    10089.0
20230309    10005.0
20230310    10103.0
20230314    10115.0
Name: value2, dtype: float64

In [ ]:
pd.merge( df2, df, how="left", on="date2")

date_x  value  change  target     date2      date_y  value2
0  2023-03-01   1000     1.5       1  20230301  2023.03.01   10005
1  2023-03-02   1010     1.3       1  20230302  2023.03.02   10103
2  2023-03-05   1008     0.9       0  20230305  2023.03.05   10089
3  2023-03-05   1011     1.5       1  20230305  2023.03.05   10089
4  2023-03-09   1000     1.5       1  20230309  2023.03.09   10005
5  2023-03-10   1010     1.3       1  20230310  2023.03.10   10103
6  2023-03-14   1008     0.9       0  20230314  2023.03.14   10115
7  2023-03-14   1011     1.5       1  20230314  2023.03.14   10115

In [ ]:
!pip install pykrx

In [ ]:
from pykrx import stock, bond

df3 = stock.get_market_ohlcv("20220720", "20220810", "005930")
df3

In [ ]:
# 다른 종목코드 찾기.
# df4 = 0730 - 0820에 대한 주가정보
# df5 = 0720 - 0810 수집
df4 = stock.get_market_ohlcv("20220730", "20220820", "086520")
df5 = stock.get_market_ohlcv("20220720", "20220810", "086520")
# 1. df3과 df4 merge
# 2. df3과 df5 concat
# 3. 086520 
result1 = pd.merge(df3, df4, how="left", on="날짜" )
result2 = pd.concat([df3, df5], axis=1 )
result2

# Date, time 실습

- Dates, Time 변수 

In [ ]:
import pandas as pd

#다양한 날짜 형식 모두 인식
pd.date_range(start='1/1/2018', end='1/08/2018')
pd.date_range(start='2018-01-01', end='1/08/2018')

#periods == 개수
pd.date_range('2019-03-05', periods=20, freq='D')
pd.date_range('2019-03-05', periods=20, freq='3M')
pd.date_range('2019-03-05', periods=20, freq='3M')
pd.date_range('2019-03-05', periods=20, freq='T')#Time간격
pd.date_range('2019-03-05', periods=20, freq='3H')

DatetimeIndex(['2019-03-05 00:00:00', '2019-03-05 03:00:00',
               '2019-03-05 06:00:00', '2019-03-05 09:00:00',
               '2019-03-05 12:00:00', '2019-03-05 15:00:00',
               '2019-03-05 18:00:00', '2019-03-05 21:00:00',
               '2019-03-06 00:00:00', '2019-03-06 03:00:00',
               '2019-03-06 06:00:00', '2019-03-06 09:00:00',
               '2019-03-06 12:00:00', '2019-03-06 15:00:00',
               '2019-03-06 18:00:00', '2019-03-06 21:00:00',
               '2019-03-07 00:00:00', '2019-03-07 03:00:00',
               '2019-03-07 06:00:00', '2019-03-07 09:00:00'],
              dtype='datetime64[ns]', freq='3H')

In [ ]:
rng_ = pd.date_range('2019-03-05', periods=20, freq='T')
type(rng_)
df = pd.DataFrame({'date': rng_})
df.head()
df.shape
df.dtypes
df["date"].dt.date
df["date"].dt.time
df

In [ ]:
df['date'].dt.time
df['date_part'] = df['date'].dt.date
df['date_part'].head()

df['time_part'] = df['date'].dt.time
df['time_part'].head()
df

In [ ]:
df = pd.DataFrame({'date_var':['Jan-2015', 'Apr-2013', 'Jun-2014','Jan-2015']})
pd.to_datetime(df['date_var'])
df['datetime_var'] = pd.to_datetime(df['date_var'])

In [ ]:
df['date'] = df['datetime_var'].dt.date
df['time'] = df['datetime_var'].dt.time
df

In [ ]:
#달과 연도 표시
import numpy as np
import pandas as pd
rng_ = pd.date_range('2019-03-05', periods=20, freq='M')
df = pd.DataFrame({'date': rng_})
df.head()
df['year'] = df['date'].dt.year
df.head()
df['month'] = df['date'].dt.month
df.head()
df['day'] = df['date'].dt.day
df.head()
df['quarter'] = df['date'].dt.quarter
df.head()

In [ ]:
#numpy의 where 조건 사용법
#isin == []에 값에 포함되어 있으면
np.where(df['quarter'].isin([1,2]), "1학기", "2학기") 

In [ ]:
df['semester'] = np.where(df['quarter'].isin([1,2]), 1, 2)  #np의 if 기능능
df.head()

In [ ]:
#day week표현
import numpy as np
import pandas as pd
rng_ = pd.date_range('2019-03-05', periods=20, freq='D')
df = pd.DataFrame({'date': rng_})
df.head()
df['day_mo'] = df['date'].dt.day
df.head()

#월요일 0부터 시작.
df['day_week'] = df['date'].dt.dayofweek
df
df['day_week'].unique()

array([1, 2, 3, 4, 5, 6, 0])

In [ ]:
df['week'] = df['date'].dt.week
df.head()

In [ ]:
#datetime에서 time 추출
import numpy as np
import pandas as pd

rng_ = pd.date_range('2019-03-05', periods=20, freq='1h15min10s')
df = pd.DataFrame({'date': rng_})
df.head()
df['hour'] = df['date'].dt.hour
df['min'] = df['date'].dt.minute
df['sec'] = df['date'].dt.second
df.head()
df.info()

In [ ]:
df[['h','m','s']] = pd.DataFrame(
    [   (x.hour, x.minute, x.second)    for x in df['date']]#한개씩..
)
df.head()
#to_datetime()를 사용하면 object에서 datetime으로 변환
df['is_morning'] = np.where( (df['hour'] < 12) & (df['hour'] > 6), 
                            1, 0 )
df.head()


In [ ]:
#datetime 변수간 측정된 기간 표현
import datetime
import numpy as np
import pandas as pd

rng_hr = pd.date_range('2019-03-05', periods=20, freq='H')
rng_month = pd.date_range('2019-03-05', periods=20, freq='M')
df = pd.DataFrame({'date1': rng_hr, 'date2': rng_month})
df.head()
df['elapsed_days'] = (df['date2'] - df['date1']).dt.days
df.head(2)

In [ ]:
df['months_passed'] = ((df['date2'] - df['date1']) / np.timedelta64(1, 'M')) #시간 간격, 월
df['months_passed'] = np.round(df['months_passed'],0) #반올림
df.head()

df['diff_seconds'] = (df['date2'] - df['date1'])/np.timedelta64(1,'s')  #시간 간격, 초
df['diff_minutes'] = (df['date2'] - df['date1'])/np.timedelta64(1,'m')  #시간 간격, 분
df.head()

In [ ]:
df['to_today'] = (datetime.datetime.today() - df['date1'])  #오늘까지의 시간
df.head()